language: c
before_script:
- git clone https://github.com/garbage-bin/android_kernel_samsung_kylevexx.git $home/android_prebuilts_gcc
script:
- export ARCH=arm
- export CROSS_COMPILE="$HOME/android_prebuilts_gcc/arm-eabi-4.6/bin/arm-eabi-"
- make -j4 bcm21664_hawaii_ss_kyleve_rev00_defconfig	
- make -j4
